<?php

namespace videoViewer\Entities;

use \Mockery as m;

/**
 * Test class for SeriesAlias.
 * Generated by PHPUnit on 2012-10-30 at 23:38:09.
 */
class SeriesAliasTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var SeriesAlias
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SeriesAlias;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    public function testGetSeries() {
        $series = m::mock('videoViewer\Entities\Series');
        $this->assertNull($this->object->getSeries());
        $this->object->setSeries($series);
        $this->assertEquals($series,$this->object->getSeries());
    }

    public function testGetAlias() {
        $this->assertEquals('',$this->object->getAlias());
        $this->object->setAlias('Series Alias');
        $this->assertEquals('Series Alias',$this->object->getAlias());
    }

}

?>
